apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: fcc-drs
  labels:
    app: fcc-drs
spec:
  # Replace with your actual hostname, e.g. fcc-drs.web.cern.ch
  host: REPLACE_WITH_HOSTNAME
  to:
    kind: Service
    name: fcc-drs
  port:
    targetPort: 5050
  tls:
    termination: edge
    insecureEdgeTerminationPolicy: Redirect
